# Nombre de la aplicación
spring.application.name=backend

# Puerto donde correrá la API REST
server.port=8080

# Conexión a la Base de Datos MySQL (Database: gym_jf)
spring.datasource.url=jdbc:mysql://localhost:3306/gym_jf?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# Usamos 'none' o 'validate' porque los scripts SQL, tablas, índices y triggers ya los creaste manualmente
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Muestra los tipos de dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuración de JWT
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
application.security.jwt.expiration=2592000000